src/main/java/cc/wdcy/domain/dto/OauthClientDetailsDto.java
package cc.wdcy.domain.dto;

import cc.wdcy.domain.oauth.OauthClientDetails;
import cc.wdcy.infrastructure.DateUtils;
import org.apache.commons.lang.StringUtils;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Shengzhao Li
 */
public class OauthClientDetailsDto implements Serializable {


    private String createTime;
    private boolean archived;

    private String clientId;
    private String resourceIds;

    private String clientSecret;

    private String scope;

    private String authorizedGrantTypes;

    private String webServerRedirectUri;

    private String authorities;

    private Integer accessTokenValidity;

    private Integer refreshTokenValidity;

    // optional
    private String additionalInformation;

    private boolean trusted;

    public OauthClientDetailsDto() {
    }

    public OauthClientDetailsDto(OauthClientDetails clientDetails) {
        this.clientId = clientDetails.clientId();
        this.clientSecret = clientDetails.clientSecret();
        this.scope = clientDetails.scope();

        this.createTime = DateUtils.toDateTime(clientDetails.createTime());
        this.archived = clientDetails.archived();
        this.resourceIds = clientDetails.resourceIds();

        this.webServerRedirectUri = clientDetails.webServerRedirectUri();
        this.authorities = clientDetails.authorities();
        this.accessTokenValidity = clientDetails.accessTokenValidity();

        this.refreshTokenValidity = clientDetails.refreshTokenValidity();
        this.additionalInformation = clientDetails.additionalInformation();
        this.trusted = clientDetails.trusted();

        this.authorizedGrantTypes = clientDetails.authorizedGrantTypes();
    }


    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public boolean isArchived() {
        return archived;
    }

    public void setArchived(boolean archived) {
        this.archived = archived;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getResourceIds() {
        return resourceIds;
    }

    public void setResourceIds(String resourceIds) {
        this.resourceIds = resourceIds;
    }

    public String getClientSecret() {
        return clientSecret;
    }

    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    public String getScope() {
        return scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public String getAuthorizedGrantTypes() {
        return authorizedGrantTypes;
    }

    public void setAuthorizedGrantTypes(String authorizedGrantTypes) {
        this.authorizedGrantTypes = authorizedGrantTypes;
    }

    public String getWebServerRedirectUri() {
        return webServerRedirectUri;
    }

    public void setWebServerRedirectUri(String webServerRedirectUri) {
        this.webServerRedirectUri = webServerRedirectUri;
    }

    public String getAuthorities() {
        return authorities;
    }

    public void setAuthorities(String authorities) {
        this.authorities = authorities;
    }

    public Integer getAccessTokenValidity() {
        return accessTokenValidity;
    }

    public void setAccessTokenValidity(Integer accessTokenValidity) {
        this.accessTokenValidity = accessTokenValidity;
    }

    public Integer getRefreshTokenValidity() {
        return refreshTokenValidity;
    }

    public void setRefreshTokenValidity(Integer refreshTokenValidity) {
        this.refreshTokenValidity = refreshTokenValidity;
    }

    public String getAdditionalInformation() {
        return additionalInformation;
    }

    public void setAdditionalInformation(String additionalInformation) {
        this.additionalInformation = additionalInformation;
    }

    public boolean isTrusted() {
        return trusted;
    }

    public void setTrusted(boolean trusted) {
        this.trusted = trusted;
    }

    public static List<OauthClientDetailsDto> toDtos(List<OauthClientDetails> clientDetailses) {
        List<OauthClientDetailsDto> dtos = new ArrayList<>(clientDetailses.size());
        for (OauthClientDetails clientDetailse : clientDetailses) {
            dtos.add(new OauthClientDetailsDto(clientDetailse));
        }
        return dtos;
    }


    public boolean isContainsAuthorizationCode() {
        return this.authorizedGrantTypes.contains("authorization_code");
    }

    public boolean isContainsPassword() {
        return this.authorizedGrantTypes.contains("password");
    }

    public boolean isContainsImplicit() {
        return this.authorizedGrantTypes.contains("implicit");
    }

    public boolean isContainsClientCredentials() {
        return this.authorizedGrantTypes.contains("client_credentials");
    }

    public boolean isContainsRefreshToken() {
        return this.authorizedGrantTypes.contains("refresh_token");
    }


    public OauthClientDetails createDomain() {
        OauthClientDetails clientDetails = new OauthClientDetails()
                .clientId(clientId)
                .clientSecret(clientSecret)
                .resourceIds(resourceIds)
                .authorizedGrantTypes(authorizedGrantTypes)
                .scope(scope);

        if (StringUtils.isNotEmpty(webServerRedirectUri)) {
            clientDetails.webServerRedirectUri(webServerRedirectUri);
        }

        if (StringUtils.isNotEmpty(authorities)) {
            clientDetails.authorities(authorities);
        }

        clientDetails.accessTokenValidity(accessTokenValidity)
                .refreshTokenValidity(refreshTokenValidity)
                .trusted(trusted);

        if (StringUtils.isNotEmpty(additionalInformation)) {
            clientDetails.additionalInformation(additionalInformation);
        }

        return clientDetails;
    }
}

src/main/java/cc/wdcy/web/controller/ClientDetailsController.java
package cc.wdcy.web.controller;

import cc.wdcy.domain.dto.OauthClientDetailsDto;
import cc.wdcy.service.OauthService;
import cc.wdcy.web.oauth.OauthClientDetailsDtoValidator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

/**
 * Handle 'client_details' management
 *
 * @author Shengzhao Li
 */
@Controller
public class ClientDetailsController {


    @Autowired
    private OauthService oauthService;

    @Autowired
    private OauthClientDetailsDtoValidator clientDetailsDtoValidator;


    @RequestMapping("client_details")
    public String clientDetails(Model model) {
        List<OauthClientDetailsDto> clientDetailsDtoList = oauthService.loadAllOauthClientDetailsDtos();
        model.addAttribute("clientDetailsDtoList", clientDetailsDtoList);
        return "clientdetails/client_details";
    }


    /*
    * Logic delete
    * */
    @RequestMapping("archive_client/{clientId}")
    public String archiveClient(@PathVariable("clientId") String clientId) {
        oauthService.archiveOauthClientDetails(clientId);
        return "redirect:../client_details";
    }

    /*
    * Test client
    * */
    @RequestMapping("test_client/{clientId}")
    public String testClient(@PathVariable("clientId") String clientId, Model model) {
        OauthClientDetailsDto clientDetailsDto = oauthService.loadOauthClientDetailsDto(clientId);
        model.addAttribute("clientDetailsDto", clientDetailsDto);
        return "clientdetails/test_client";
    }


    /*
    * Register client
    * */
    @RequestMapping(value = "register_client", method = RequestMethod.GET)
    public String registerClient(Model model) {
        model.addAttribute("formDto", new OauthClientDetailsDto());
        return "clientdetails/register_client";
    }


    /*
    * Submit register client
    * */
    @RequestMapping(value = "register_client", method = RequestMethod.POST)
    public String submitRegisterClient(@ModelAttribute("formDto") OauthClientDetailsDto formDto, BindingResult result) {
        clientDetailsDtoValidator.validate(formDto, result);
        if (result.hasErrors()) {
            return "clientdetails/register_client";
        }
        oauthService.registerClientDetails(formDto);
        return "redirect:client_details";
    }


}

src/main/webapp/WEB-INF/jsp/clientdetails/client_details.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>client_details</title>

    <style>
        .list-group li:hover {
            background-color: #f9f9f9;
        }
    </style>
</head>
<body>
<a href="./">Home</a>

<div class="row">
    <div class="col-md-10">
        <h3>client_details</h3>
    </div>
    <div class="col-md-2">
        <div class="pull-right">
            <a href="register_client" class="btn btn-success btn-sm">注册client</a>
        </div>
    </div>
</div>

<hr/>

<div>
    <ul class="list-group">
        <c:forEach items="${clientDetailsDtoList}" var="cli">
            <li class="list-group-item">
                <div class="pull-right">
                    <c:if test="${not cli.archived}">
                        <a href="test_client/${cli.clientId}">test</a>
                        <a href="archive_client/${cli.clientId}" class="text-danger"
                           onclick="return confirm('Are you sure archive \'${cli.clientId}\'?')">archive</a>
                    </c:if>
                    <c:if test="${cli.archived}"><strong class="text-muted">Archived</strong></c:if>
                </div>
                <h3 class="list-group-item-heading">
                        ${cli.clientId}
                    <small>${cli.authorizedGrantTypes}</small>
                </h3>

                <div class="list-group-item-text text-muted">
                    client_id: <span class="text-danger">${cli.clientId}</span>&nbsp;
                    client_secret: <span class="text-primary">${cli.clientSecret}</span>&nbsp;
                    <br/>
                    authorized_grant_types: <span class="text-primary">${cli.authorizedGrantTypes}</span>&nbsp;
                    resource_ids: <span class="text-primary">${cli.resourceIds}</span>&nbsp;
                    <br/>
                    scope: <span class="text-primary">${cli.scope}</span>&nbsp;
                    web_server_redirect_uri: <span class="text-primary">${cli.webServerRedirectUri}</span>&nbsp;
                    <br/>
                    authorities: <span class="text-primary">${cli.authorities}</span>&nbsp;
                    access_token_validity: <span class="text-primary">${cli.accessTokenValidity}</span>&nbsp;
                    refresh_token_validity: <span class="text-primary">${cli.refreshTokenValidity}</span>&nbsp;
                    <br/>
                    create_time: <span class="text-primary">${cli.createTime}</span>&nbsp;
                    archived: <strong class="${cli.archived?'text-warning':'text-primary'}">${cli.archived}</strong>&nbsp;
                    trusted: <span class="text-primary">${cli.trusted}</span>&nbsp;
                    additional_information: <span class="text-primary">${cli.additionalInformation}</span>&nbsp;
                </div>
            </li>
        </c:forEach>

    </ul>
    <p class="help-block">
        每一个item对应<code>oauth_client_details</code>表中的一条数据; 共<strong>${fun:length(clientDetailsDtoList)}</strong>条数据.
        <br/>
        对spring-oauth-server数据库表的详细说明请访问
        <a href="http://andaily.com/spring-oauth-server/db_table_description.html" target="_blank">http://andaily.com/spring-oauth-server/db_table_description.html</a>
        (或访问项目others目录的db_table_description.html文件)
    </p>
</div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/clientdetails/register_client.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>注册client</title>
    <script src="${contextPath}/resources/angular.min.js"></script>

</head>
<body>
<a href="./">Home</a>

<h2>注册client</h2>

<div ng-app>
<p class="help-block">
    若对Oauth的<code>client_details</code>中的属性及作用不清楚,
    建议你先查看项目中的<code>db_table_description.html</code>文件(位于others目录)中对表<code>oauth_client_details</code>的说明,
    或在线访问<a href="http://andaily.com/spring-oauth-server/db_table_description.html" target="_blank">db_table_description.html</a>;
    因为注册client实际上是向该表中按不同的条件添加数据.
</p>

<div ng-controller="RegisterClientCtrl">
        <form:form commandName="formDto" cssClass="form-horizontal">
            <div class="form-group">
                <label for="clientId" class="col-sm-2 control-label">client_id<em class="text-danger">*</em></label>

                <div class="col-sm-10">
                    <form:input path="clientId" cssClass="form-control" id="clientId" placeholder="client_id"
                                required="required"/>

                    <p class="help-block">client_id必须输入,且必须唯一,长度至少5位; 在实际应用中的另一个名称叫appKey,与client_id是同一个概念.</p>
                </div>
            </div>
            <div class="form-group">
                <label for="clientSecret" class="col-sm-2 control-label">client_secret<em
                        class="text-danger">*</em></label>

                <div class="col-sm-10">
                    <form:input path="clientSecret" cssClass="form-control" id="clientSecret"
                                placeholder="client_secret" required="required"/>

                    <p class="help-block">client_secret必须输入,且长度至少8位; 在实际应用中的另一个名称叫appSecret,与client_secret是同一个概念.</p>
                </div>
            </div>
            <div class="form-group">
                <label for="resourceIds" class="col-sm-2 control-label">resource_ids<em
                        class="text-danger">*</em></label>

                <div class="col-sm-10">
                    <form:select path="resourceIds" cssClass="form-control" id="resourceIds">
                        <form:option value="unity-resource">unity-resource</form:option>
                        <form:option value="mobile-resource">mobile-resource</form:option>
                        <form:option value="unity-resource,mobile-resource">unity-resource,mobile-resource</form:option>
                    </form:select>

                    <p class="help-block">resourceIds必须选择; 可选值必须来源于与<code>security.xml</code>中标签<code>&lsaquo;oauth2:resource-server</code>的属性<code>resource-id</code>值
                    </p>
                </div>
            </div>

            <div class="form-group">
                <label for="scope" class="col-sm-2 control-label">scope<em class="text-danger">*</em></label>

                <div class="col-sm-10">
                    <form:select path="scope" id="scope" cssClass="form-control">
                        <form:option value="read">read</form:option>
                        <form:option value="write">write</form:option>
                        <form:option value="trust">trust</form:option>
                        <form:option value="read,write">read,write</form:option>
                    </form:select>

                    <p class="help-block">scope必须选择</p>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">grant_type(s)<em class="text-danger">*</em></label>

                <div class="col-sm-10">
                    <label class="checkbox-inline">
                        <input type="checkbox" name="authorizedGrantTypes"
                               value="authorization_code" ${fun:containsIgnoreCase(formDto.authorizedGrantTypes, 'authorization_code') ?'checked':''} />
                        authorization_code
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="authorizedGrantTypes"
                               value="password" ${fun:containsIgnoreCase(formDto.authorizedGrantTypes, 'authorization_code') ?'checked':''} />
                        password
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="authorizedGrantTypes"
                               value="implicit" ${fun:containsIgnoreCase(formDto.authorizedGrantTypes, 'implicit') ?'checked':''} />
                        implicit
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="authorizedGrantTypes"
                               value="client_credentials" ${fun:containsIgnoreCase(formDto.authorizedGrantTypes, 'client_credentials') ?'checked':''} />
                        client_credentials
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="authorizedGrantTypes"
                               value="refresh_token" ${fun:containsIgnoreCase(formDto.authorizedGrantTypes, 'refresh_token') ?'checked':''} />
                        refresh_token
                    </label>

                    <p class="help-block">至少勾选一项grant_type(s), 且不能只单独勾选<code>refresh_token</code></p>
                </div>
            </div>

            <div class="form-group">
                <label for="webServerRedirectUri" class="col-sm-2 control-label">redirect_uri</label>

                <div class="col-sm-10">
                    <form:input path="webServerRedirectUri" id="webServerRedirectUri" placeholder="redirect_uri"
                                cssClass="form-control"/>

                    <p class="help-block">若<code>grant_type</code>包括<em>authorization_code</em>或<em>implicit</em>,
                        则必须输入redirect_uri</p>
                </div>
            </div>

            <div class="form-group">
                <label for="authorities" class="col-sm-2 control-label">authorities</label>

                <div class="col-sm-10">
                    <form:select path="authorities" id="authorities" cssClass="form-control">
                        <form:option value="">无</form:option>
                        <form:option value="ROLE_USER,ROLE_UNITY">ROLE_UNITY</form:option>
                        <form:option value="ROLE_USER,ROLE_MOBILE">ROLE_MOBILE</form:option>
                        <form:option value="ROLE_USER,ROLE_UNITY,ROLE_MOBILE">ROLE_UNITY,ROLE_MOBILE</form:option>
                    </form:select>

                    <p class="help-block">指定客户端所拥有的Spring Security的权限值,可选;
                        若<code>grant_type</code>为<em>implicit</em>或<em>client_credentials</em>则必须选择authorities,
                        因为服务端将根据该字段值的权限来判断是否有权限访问对应的API</p>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <a href="javascript:void(0);" ng-click="showMore()">更多选项</a>
                </div>
            </div>

            <div ng-show="visible">
                <div class="form-group">
                    <label for="accessTokenValidity" class="col-sm-2 control-label">access_token_validity</label>

                    <div class="col-sm-10">
                        <input type="number" class="form-control" name="accessTokenValidity" id="accessTokenValidity"
                               placeholder="access_token_validity"/>

                        <p class="help-block">设定客户端的access_token的有效时间值(单位:秒),可选, 若不设定值则使用默认的有效时间值(60 * 60 * 12, 12小时);
                            若设定则必须是大于0的整数值</p>
                    </div>
                </div>

                <div class="form-group">
                    <label for="refreshTokenValidity" class="col-sm-2 control-label">refresh_token_validity</label>

                    <div class="col-sm-10">
                        <input type="number" class="form-control" name="refreshTokenValidity" id="refreshTokenValidity"
                               placeholder="refresh_token_validity"/>

                        <p class="help-block">设定客户端的refresh_token的有效时间值(单位:秒),可选, 若不设定值则使用默认的有效时间值(60 * 60 * 24 * 30,
                            30天);
                            若设定则必须是大于0的整数值</p>
                    </div>
                </div>

                <div class="form-group">
                    <label for="additionalInformation" class="col-sm-2 control-label">additional_information</label>

                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="additionalInformation" id="additionalInformation"
                               placeholder="additional_information"/>

                        <p class="help-block">
                            这是一个预留的字段,在Oauth的流程中没有实际的使用,可选,但若设置值,必须是JSON格式的数据,如:
                            <code>{"country":"CN","country_code":"086"}</code>
                        </p>
                    </div>
                </div>


                <div class="form-group">
                    <label class="col-sm-2 control-label">trusted</label>

                    <div class="col-sm-10">
                        <label class="radio-inline">
                            <input type="radio" name="trusted" value="true"/> Yes
                        </label>
                        <label class="radio-inline">
                            <input type="radio" name="trusted" value="false" checked="checked"/> No
                        </label>

                        <p class="help-block">该属性是扩展的,
                            只适用于grant_type(s)包括<code>authorization_code</code>的情况,当用户登录成功后,若选No,则会跳转到让用户Approve的页面让用户同意授权,
                            若选Yes,则在登录后不需要再让用户Approve同意授权(因为是受信任的)</p>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <form:errors path="*" cssClass="text-danger"/>
                </div>
            </div>


            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-success">注册</button>
                    <a href="client_details">取消</a>
                </div>
            </div>
        </form:form>
    </div>
</div>

<script>
    var RegisterClientCtrl = ["$scope", function ($scope) {
        $scope.visible = false;

        $scope.showMore = function () {
            $scope.visible = !$scope.visible;
        };
    }];
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/clientdetails/test_client.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Test [${clientDetailsDto.clientId}]</title>

    <script src="${contextPath}/resources/angular.min.js"></script>

</head>
<body>
<div ng-app>
    <a href="../">Home</a>

    <h2>Test [${clientDetailsDto.clientId}]</h2>

    <p>
        针对不同的<code>grant_type</code>提供不同的测试URL,
        完整的Oauth测试请访问<a href="http://git.oschina.net/mkk/spring-oauth-client" target="_blank">spring-oauth-client</a>项目.
    </p>

    <div ng-controller="TestClientCtrl">
        <c:if test="${clientDetailsDto.containsAuthorizationCode}">
            <div class="panel panel-default">
                <div class="panel-heading">Test [authorization_code]</div>
                <div class="panel-body">
                    <p class="text-muted">输入每一步必要的信息后点击其下面的链接地址.</p>
                    <ol>
                        <li>
                            <p>
                                <code>从 spring-oauth-server获取 'code'</code>
                                <br/>
                                redirect_uri: <input type="text" value="" ng-model="redirectUri" size="70"
                                                     required="required"/>
                                <br/>
                                <a href="${contextPath}/oauth/authorize?client_id={{clientId}}&redirect_uri={{redirectUri}}&response_type=code&scope={{scope}}"
                                   target="_blank">
                                    /oauth/authorize?client_id={{clientId}}&redirect_uri={{redirectUri}}&response_type=code&scope={{scope}}</a>
                            </p>
                        </li>
                        <li>
                            <p>
                                <code>用 'code' 换取 'access_token'</code>
                                <br/>
                                输入第一步获取的code: <input type="text" name="code" value="" ng-model="code"
                                                     required="required"/>
                                <br/>
                                <a href="${contextPath}/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=authorization_code&code={{code}}&redirect_uri={{redirectUri}}"
                                   target="_blank">/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=authorization_code&code={{code}}&redirect_uri={{redirectUri}}</a>
                            </p>
                        </li>
                    </ol>
                </div>
            </div>
        </c:if>

        <c:if test="${clientDetailsDto.containsPassword}">
            <div class="panel panel-default">
                <div class="panel-heading">Test [password]</div>
                <div class="panel-body">
                    <p class="text-muted">输入username, password 后点击链接地址.</p>
                    username: <input type="text" required="required" ng-model="username"/>
                    <br/>
                    password: <input type="text" required="required" ng-model="password"/>

                    <p>
                        <a href="${contextPath}/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=password&scope={{scope}}&username={{username}}&password={{password}}"
                           target="_blank">/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=password&scope={{scope}}&username={{username}}&password={{password}}</a>
                    </p>
                </div>
            </div>
        </c:if>

        <c:if test="${clientDetailsDto.containsImplicit}">
            <div class="panel panel-default">
                <div class="panel-heading">Test [implicit]</div>
                <div class="panel-body">
                    <p class="text-muted">输入redirect_uri 后点击链接地址. 获取access_token后注意查看redirect_uri的hash部分(#号后边部分)</p>
                    redirect_uri: <input type="text" value="" ng-model="implicitRedirectUri" size="70"
                                         required="required"/>

                    <p>
                        <a href="${contextPath}/oauth/authorize?client_id={{clientId}}&client_secret={{clientSecret}}&response_type=token&scope={{scope}}&redirect_uri={{implicitRedirectUri}}"
                                >/oauth/authorize?client_id={{clientId}}&client_secret={{clientSecret}}&response_type=token&scope={{scope}}&redirect_uri={{implicitRedirectUri}}</a>
                    </p>
                </div>
            </div>
        </c:if>

        <c:if test="${clientDetailsDto.containsClientCredentials}">
            <div class="panel panel-default">
                <div class="panel-heading">Test [client_credentials]</div>
                <div class="panel-body">
                    <p class="text-muted">点击链接地址即可测试</p>

                    <p>
                        <a href="${contextPath}/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=client_credentials&scope={{scope}}"
                           target="_blank">/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=client_credentials&scope={{scope}}</a>
                    </p>
                </div>
            </div>
        </c:if>

        <c:if test="${clientDetailsDto.containsRefreshToken}">
            <div class="panel panel-default">
                <div class="panel-heading">Test [refresh_token]</div>
                <div class="panel-body">
                    <p class="text-muted">输入refresh_token 后点击链接地址.</p>
                    refresh_token: <input type="text" ng-model="refreshToken" required="required" size="70"/>

                    <p>
                        <a href="${contextPath}/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=refresh_token&refresh_token={{refreshToken}}"
                           target="_blank">/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=refresh_token&refresh_token={{refreshToken}}</a>
                    </p>
                </div>
            </div>
        </c:if>

        <div class="text-center">
            <a href="${contextPath}/client_details" class="btn btn-info">Back</a>
        </div>
    </div>
</div>

<script>
    var TestClientCtrl = ["$scope", function ($scope) {
        $scope.clientId = "${clientDetailsDto.clientId}";
        $scope.clientSecret = "${clientDetailsDto.clientSecret}";
        $scope.scope = "${clientDetailsDto.scope}";

        <c:if test="${empty clientDetailsDto.webServerRedirectUri}" var="eptRedUri">
        $scope.implicitRedirectUri = location.href;
        $scope.redirectUri = "http://localhost:8080/spring-oauth-server/unity/dashboard";
        </c:if>
        <c:if test="${not eptRedUri}">
        $scope.implicitRedirectUri = "${clientDetailsDto.webServerRedirectUri}";
        $scope.redirectUri = "${clientDetailsDto.webServerRedirectUri}";
        </c:if>

        $scope.username = "mobile";
        $scope.password = "mobile";
        //a temp value
        $scope.refreshToken = "1156ebfe-e303-4572-9fb5-4459a5d46610";

    }];
</script>
</body>
</html>